/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiPeopleRouteImport } from './routes/api/people'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeopleRoute = ApiPeopleRouteImport.update({
  id: '/api/people',
  path: '/api/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/data': typeof ApiDataRoute
  '/api/people': typeof ApiPeopleRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/data': typeof ApiDataRoute
  '/api/people': typeof ApiPeopleRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/data': typeof ApiDataRoute
  '/api/people': typeof ApiPeopleRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/data'
    | '/api/people'
    | '/api/settings'
    | '/api/upload'
    | '/api/uploads/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/data'
    | '/api/people'
    | '/api/settings'
    | '/api/upload'
    | '/api/uploads/$'
  id:
    | '__root__'
    | '/'
    | '/api/data'
    | '/api/people'
    | '/api/settings'
    | '/api/upload'
    | '/api/uploads/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiPeopleRoute: typeof ApiPeopleRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/people': {
      id: '/api/people'
      path: '/api/people'
      fullPath: '/api/people'
      preLoaderRoute: typeof ApiPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDataRoute: ApiDataRoute,
  ApiPeopleRoute: ApiPeopleRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
